name: "Claude Max Code Base Action"
description: "Run Claude Code in GitHub Actions workflows with your Claude Max subscription."
branding:
  icon: "code"
  color: "orange"

inputs:
  # Claude Code arguments
  prompt:
    description: "The prompt to send to Claude Code (mutually exclusive with prompt_file)"
    required: false
    default: ""
  prompt_file:
    description: "Path to a file containing the prompt to send to Claude Code (mutually exclusive with prompt)"
    required: false
    default: ""
  allowed_tools:
    description: "Comma-separated list of allowed tools for Claude Code to use"
    required: false
    default: ""
  disallowed_tools:
    description: "Comma-separated list of disallowed tools that Claude Code cannot use"
    required: false
    default: ""
  max_turns:
    description: "Maximum number of conversation turns (default: no limit)"
    required: false
    default: ""
  mcp_config:
    description: "MCP configuration as JSON string or path to MCP configuration JSON file"
    required: false
    default: ""
  model:
    description: "Model to use (provider-specific format required for Bedrock/Vertex)"
    required: false
  anthropic_model:
    description: "DEPRECATED: Use 'model' instead. Model to use (provider-specific format required for Bedrock/Vertex)"
    required: false

  # Action settings
  timeout_minutes:
    description: "Timeout in minutes for Claude Code execution"
    required: false
    default: "10"

  # Authentication settings
  anthropic_api_key:
    description: "Anthropic API key (required for direct Anthropic API)"
    required: false
    default: ""
  use_bedrock:
    description: "Use Amazon Bedrock with OIDC authentication instead of direct Anthropic API"
    required: false
    default: "false"
  use_vertex:
    description: "Use Google Vertex AI with OIDC authentication instead of direct Anthropic API"
    required: false
    default: "false"
  use_oauth:
    description: "Use Claude AI OAuth authentication instead of API key"
    required: false
    default: "false"
  claude_access_token:
    description: "Claude AI OAuth access token (required when use_oauth is true)"
    required: false
    default: ""
  claude_refresh_token:
    description: "Claude AI OAuth refresh token (required when use_oauth is true)"
    required: false
    default: ""
  claude_expires_at:
    description: "Claude AI OAuth token expiration timestamp (required when use_oauth is true)"
    required: false
    default: ""

  use_node_cache:
    description: "Whether to use Node.js dependency caching (set to true only for Node.js projects with lock files)"
    required: false
    default: "false"

outputs:
  conclusion:
    description: "Execution status of Claude Code ('success' or 'failure')"
    value: ${{ steps.run_claude.outputs.conclusion }}
  execution_file:
    description: "Path to the JSON file containing Claude Code execution log"
    value: ${{ steps.run_claude.outputs.execution_file }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # https://github.com/actions/setup-node/releases/tag/v4.4.0
      with:
        node-version: "18.x"
        cache: ${{ inputs.use_node_cache == 'true' && 'npm' || '' }}

    - name: Install Bun
      uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # https://github.com/oven-sh/setup-bun/releases/tag/v2.0.2
      with:
        bun-version: 1.2.11

    - name: Install Dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        bun install

    - name: Install Claude Code
      shell: bash
      run: npm install -g @anthropic-ai/claude-code@1.0.2

    - name: Run Claude Code Action
      shell: bash
      id: run_claude
      run: |
        bun run ${{ github.action_path }}/src/index.ts
      env:
        # Model configuration
        CLAUDE_CODE_ACTION: "1"
        ANTHROPIC_MODEL: ${{ inputs.model || inputs.anthropic_model }}
        INPUT_PROMPT: ${{ inputs.prompt }}
        INPUT_PROMPT_FILE: ${{ inputs.prompt_file }}
        INPUT_ALLOWED_TOOLS: ${{ inputs.allowed_tools }}
        INPUT_DISALLOWED_TOOLS: ${{ inputs.disallowed_tools }}
        INPUT_MAX_TURNS: ${{ inputs.max_turns }}
        INPUT_MCP_CONFIG: ${{ inputs.mcp_config }}
        INPUT_TIMEOUT_MINUTES: ${{ inputs.timeout_minutes }}

        # Provider configuration
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        # Only set provider flags if explicitly true, since any value (including "false") is truthy
        CLAUDE_CODE_USE_BEDROCK: ${{ inputs.use_bedrock == 'true' && '1' || '' }}
        CLAUDE_CODE_USE_VERTEX: ${{ inputs.use_vertex == 'true' && '1' || '' }}
        CLAUDE_CODE_USE_OAUTH: ${{ inputs.use_oauth == 'true' && '1' || '' }}

        # OAuth configuration
        CLAUDE_ACCESS_TOKEN: ${{ inputs.claude_access_token }}
        CLAUDE_REFRESH_TOKEN: ${{ inputs.claude_refresh_token }}
        CLAUDE_EXPIRES_AT: ${{ inputs.claude_expires_at }}

        # AWS configuration
        AWS_REGION: ${{ env.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
        ANTHROPIC_BEDROCK_BASE_URL: ${{ env.ANTHROPIC_BEDROCK_BASE_URL || (env.AWS_REGION && format('https://bedrock-runtime.{0}.amazonaws.com', env.AWS_REGION)) }}

        # GCP configuration
        ANTHROPIC_VERTEX_PROJECT_ID: ${{ env.ANTHROPIC_VERTEX_PROJECT_ID }}
        CLOUD_ML_REGION: ${{ env.CLOUD_ML_REGION }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        ANTHROPIC_VERTEX_BASE_URL: ${{ env.ANTHROPIC_VERTEX_BASE_URL }}
